import 'dotenv/config'

import { spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { Client } from 'pg'

type JournalEntry = {
  idx: number
  when: number
  tag: string
}

const journalPath = fileURLToPath(
  new URL('../src/db/migrations/meta/_journal.json', import.meta.url)
)

const migrationPath = (tag: string) =>
  fileURLToPath(new URL(`../src/db/migrations/${tag}.sql`, import.meta.url))

const requiredLegacyTables = [
  'account',
  'comments',
  'likes',
  'posts',
  'session',
  'user',
  'verification',
  'views',
] as const

const MIGRATION_BOOTSTRAP_LOCK_KEYS: [number, number] = [39124, 1604]

const sha256 = (value: string) =>
  createHash('sha256').update(value, 'utf8').digest('hex')

const loadJournalEntries = (): JournalEntry[] => {
  const parsed = JSON.parse(readFileSync(journalPath, 'utf8')) as {
    entries: JournalEntry[]
  }

  return parsed.entries
}

const tableExists = async (client: Client, schema: string, table: string) => {
  const result = await client.query<{ exists: boolean }>(
    `
      select exists (
        select 1
        from information_schema.tables
        where table_schema = $1 and table_name = $2
      ) as exists
    `,
    [schema, table]
  )

  return Boolean(result.rows[0]?.exists)
}

const columnExists = async (client: Client, table: string, column: string) => {
  const result = await client.query<{ exists: boolean }>(
    `
      select exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = $1
          and column_name = $2
      ) as exists
    `,
    [table, column]
  )

  return Boolean(result.rows[0]?.exists)
}

const constraintExists = async (
  client: Client,
  table: string,
  constraint: string
) => {
  const result = await client.query<{ exists: boolean }>(
    `
      select exists (
        select 1
        from pg_constraint constraint_def
        inner join pg_class relation on relation.oid = constraint_def.conrelid
        inner join pg_namespace namespace on namespace.oid = relation.relnamespace
        where namespace.nspname = 'public'
          and relation.relname = $1
          and constraint_def.conname = $2
      ) as exists
    `,
    [table, constraint]
  )

  return Boolean(result.rows[0]?.exists)
}

const generatedColumnExpression = async (
  client: Client,
  table: string,
  column: string
) => {
  const result = await client.query<{ expression: string | null }>(
    `
      select pg_get_expr(definition.adbin, definition.adrelid) as expression
      from pg_attribute attribute
      inner join pg_class relation on relation.oid = attribute.attrelid
      inner join pg_namespace namespace on namespace.oid = relation.relnamespace
      left join pg_attrdef definition
        on definition.adrelid = attribute.attrelid
       and definition.adnum = attribute.attnum
      where namespace.nspname = 'public'
        and relation.relname = $1
        and attribute.attname = $2
        and attribute.attisdropped = false
      limit 1
    `,
    [table, column]
  )

  return result.rows[0]?.expression ?? null
}

const indexExists = async (
  client: Client,
  table: string,
  index: string
) => {
  const result = await client.query<{ exists: boolean }>(
    `
      select exists (
        select 1
        from pg_indexes
        where tablename = $1
          and indexname = $2
      ) as exists
    `,
    [table, index]
  )

  return Boolean(result.rows[0]?.exists)
}

const ensureMigrationJournal = async (client: Client) => {
  await client.query('create schema if not exists drizzle')
  await client.query(`
    create table if not exists drizzle.__drizzle_migrations (
      id integer primary key generated by default as identity,
      hash text not null,
      created_at bigint
    )
  `)
}

const detectLegacyBaselineIdx = async (client: Client) => {
  for (const table of requiredLegacyTables) {
    const exists = await tableExists(client, 'public', table)
    if (!exists) return null
  }

  if (await columnExists(client, 'posts', 'search_vector')) {
    const hasIndex = await indexExists(client, 'posts', 'idx_posts_search')

    if (hasIndex) {
      // Both column and index exist - check expression to determine migration 3 or 4
      const expression = await generatedColumnExpression(
        client,
        'posts',
        'search_vector'
      )

      if (expression?.includes("'english'")) return 4

      return 3
    }

    // Column exists but index doesn't - don't advance baseline to 3 or 4,
    // fall through to check earlier migration markers
  }
  if (await columnExists(client, 'views', 'viewer_ip_hash')) return 2
  if (await constraintExists(client, 'views', 'view_actor_required_check')) {
    return 1
  }

  return 0
}

const bootstrapLegacyJournalIfNeeded = async (client: Client) => {
  await client.query('begin')

  try {
    await client.query(
      'select pg_advisory_xact_lock($1, $2)',
      MIGRATION_BOOTSTRAP_LOCK_KEYS
    )
    await ensureMigrationJournal(client)

    const migrationCount = await client.query<{ count: string }>(
      'select count(*)::text as count from drizzle.__drizzle_migrations'
    )
    const count = Number(migrationCount.rows[0]?.count ?? '0')

    if (count > 0) {
      await client.query('commit')
      return
    }

    const baselineIdx = await detectLegacyBaselineIdx(client)
    if (baselineIdx === null) {
      await client.query('commit')
      return
    }

    const entries = loadJournalEntries().filter(
      (entry) => entry.idx <= baselineIdx
    )
    if (entries.length === 0) {
      await client.query('commit')
      return
    }

    for (const entry of entries) {
      const sql = readFileSync(migrationPath(entry.tag), 'utf8')
      await client.query(
        `
          insert into drizzle.__drizzle_migrations (hash, created_at)
          values ($1, $2)
        `,
        [sha256(sql), entry.when]
      )
    }

    await client.query('commit')

    console.log(
      `Bootstrapped Drizzle journal with ${entries.length} legacy migration(s).`
    )
  } catch (error) {
    await client.query('rollback')
    throw error
  }
}

const run = async () => {
  const databaseUrl = process.env['DATABASE_URL']

  if (!databaseUrl) {
    throw new Error('DATABASE_URL is required to run migrations')
  }

  const client = new Client({
    connectionString: databaseUrl,
  })

  await client.connect()

  try {
    await bootstrapLegacyJournalIfNeeded(client)
  } finally {
    await client.end()
  }

  const result = spawnSync('bunx', ['drizzle-kit', 'migrate'], {
    stdio: 'inherit',
    env: process.env,
  })

  if (result.error) throw result.error
  if (result.status !== 0) process.exit(result.status ?? 1)
}

await run()